# Apollo Linux — LightDM Configuration
# /etc/lightdm/lightdm.conf

[LightDM]
# Greeter configuration
greeter-session=lightdm-gtk-greeter
sessions-directory=/usr/share/xsessions:/usr/share/wayland-sessions
logind-check-graphical=true
minimum-display-number=0

[Seat:*]
# Session management
session-wrapper=/etc/lightdm/Xsession
greeter-hide-users=false
greeter-show-manual-login=false
allow-guest=false

# Auto-login (disabled by default — Calamares sets this if user requests)
autologin-user=root
autologin-user-timeout=0
autologin-session=openbox

[XDMCPServer]
enabled=false

[VNCServer]
enabled=false
